<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <title>Projects Report</title>
    <style>
        body { font-family: sans-serif; color: #333; }
        .header { text-align: center; margin-bottom: 30px; }
        .header h1 { color: #1b8c00; margin: 0; }
        .header p { color: #666; margin: 5px 0 0 0; }
        table { width: 100%; border-collapse: collapse; margin-top: 20px; }
        th { background-color: #1b8c00; color: white; text-align: left; padding: 10px; font-size: 12px; }
        td { padding: 10px; border-bottom: 1px solid #eee; font-size: 11px; }
        .status { font-weight: bold; }
        .footer { position: fixed; bottom: 0; width: 100%; text-align: right; font-size: 10px; color: #aaa; }
    </style>
</head>
<body>
    <div class="header">
        <h1>E-CES Tracker</h1>
        <p>Projects & Impact Report - {{ date('M d, Y') }}</p>
    </div>

    <table>
        <thead>
            <tr>
                <th>Project Name</th>
                <th>Status</th>
                <th>Budget</th>
                <th>Community</th>
                <th>Date</th>
            </tr>
        </thead>
        <tbody>
            @foreach($projects as $project)
                <tr>
                    <td><strong>{{ $project->project_name }}</strong></td>
                    <td class="status">{{ ucfirst($project->status) }}</td>
                    <td>Php {{ number_format($project->budget, 2) }}</td>
                    <td>{{ $project->events->first()?->community?->community_name ?? 'N/A' }}</td>
                    <td>{{ $project->created_at->format('Y-m-d') }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    <div class="footer">
        Generated by E-CES Tracker System
    </div>
</body>
</html>
